Client Failed To Connect To The Database Exception Thrown: 2024-05-18 22:31
se.kth.iv1350.seminar4.integration.DatabaseUnresponsiveException: Client Failed To Connect To The Database
	at se.kth.iv1350.seminar4.integration.ExternalInventorySystemAccessPoint.retrieveItem(ExternalInventorySystemAccessPoint.java:66)
	at se.kth.iv1350.seminar4.controller.Controller.addItem(Controller.java:108)
	at se.kth.iv1350.seminar4.view.View.fakeCustomer(View.java:99)
	at se.kth.iv1350.seminar4.startup.Main.main(Main.jClient Failed To Connect To The Database Exception Thrown: 2024-05-18 23:32
se.kth.iv1350.seminar4.integration.DatabaseUnresponsiveException: Client Failed To Connect To The Database
	at se.kth.iv1350.seminar4.integration.ExternalInventorySystemAccessPoint.retrieveItem(ExternalInventorySystemAccessPoint.java:66)
	at se.kth.iv1350.seminar4.controller.Controller.addItem(Controller.java:110)
	at se.kth.iv1350.seminar4.view.View.fakeCustomer(View.java:100)
	at se.kth.iv1350.seminar4.startup.Main.main(Main.